name: kir-tube
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - kir-tube-network
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: kir-tube-db
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/data/postgres
    networks:
      - kir-tube-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    env_file:
      - ./.env
    command: server --console-address ":9001" /data
    restart: always
    networks:
      - kir-tube-network
volumes:
  postgres_data:
  minio-data:
networks:
  kir-tube-network:
    driver: bridge
